#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
#
# Automatically adds branch name and branch description to every commit message.
#
BRANCH_NAME=$(git branch | grep '*' | sed 's/* //')

echo ["$BRANCH_NAME"]': '$(cat "$1") > "$1"
if [ -n "$DESCRIPTION" ] 
then
  echo "" >> "$1"
fi 

# https://stackoverflow.com/questions/5894946/how-to-add-gits-branch-name-to-the-commit-message
