name: 'test-coverage-report'
on:
  pull_request_target:
    branches:
      - develop
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          package-manager: yarn
